In [23]:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_datasets as tfds

In [24]:
tf.executing_eagerly()

True

In [25]:
print(tf.__version__)
print(hub.__version__)

2.19.0
0.16.1


In [26]:
# Check GPU

tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [27]:
# dataset
import tensorflow_datasets as tfds
train_data, validation_data, test_data = tfds.load(
    name="imdb_reviews", 
    split=('train[:60%]', 'train[60%:]', 'test'),
    as_supervised=True,
    batch_size=32
   )

In [28]:
len(train_data), len(validation_data), len(test_data)

(469, 313, 782)

In [29]:
train_examples_batch, train_labels_batch = next(iter(train_data))
train_labels_batch

2025-05-14 15:51:43.689913: W tensorflow/core/kernels/data/cache_dataset_ops.cc:916] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


<tf.Tensor: shape=(32,), dtype=int64, numpy=
array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0])>

In [30]:
train_examples_batch[:1]

<tf.Tensor: shape=(1,), dtype=string, numpy=
array([b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it."],
      dtype=object)>

In [31]:
embedding = "https://tfhub.dev/google/nnlm-en-dim50/2"
hub_layer = hub.KerasLayer(embedding, input_shape=[], 
                           dtype=tf.string, trainable=True)
hub_layer(train_examples_batch[:1])

<tf.Tensor: shape=(1, 50), dtype=float32, numpy=
array([[ 0.5423195 , -0.0119017 ,  0.06337538,  0.06862972, -0.16776837,
        -0.10581174,  0.16865303, -0.04998824, -0.31148055,  0.07910346,
         0.15442263,  0.01488662,  0.03930153,  0.19772711, -0.12215476,
        -0.04120981, -0.2704109 , -0.21922152,  0.26517662, -0.80739075,
         0.25833532, -0.3100421 ,  0.28683215,  0.1943387 , -0.29036492,
         0.03862849, -0.7844411 , -0.0479324 ,  0.4110299 , -0.36388892,
        -0.58034706,  0.30269456,  0.3630897 , -0.15227164, -0.44391504,
         0.19462997,  0.19528408,  0.05666234,  0.2890704 , -0.28468323,
        -0.00531206,  0.0571938 , -0.3201318 , -0.04418665, -0.08550783,
        -0.55847436, -0.23336391, -0.20782952, -0.03543064, -0.17533456]],
      dtype=float32)>

In [32]:
import tf_keras
model = tf_keras.Sequential([
    hub_layer,
    tf_keras.layers.Dense(16, activation='relu'),
    tf_keras.layers.Dense(1)
    
])


model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   


 keras_layer_1 (KerasLayer)  (None, 50)                48190600  
                                                                 
 dense_2 (Dense)             (None, 16)                816       
                                                                 
 dense_3 (Dense)             (None, 1)                 17        
                                                                 
Total params: 48191433 (183.84 MB)
Trainable params: 48191433 (183.84 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [33]:
model.compile(optimizer='adam',
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=['accuracy'])

In [35]:
history = model.fit(train_data.shuffle(10000).batch(32),
                    epochs=10,
                    validation_data=validation_data.batch(32),
                    verbose=1)

Epoch 1/10


TypeError: in user code:

    File "/Users/sachinmurali/anaconda3/envs/tensorflows/lib/python3.11/site-packages/tf_keras/src/engine/training.py", line 1398, in train_function  *
        return step_function(self, iterator)
    File "/Users/sachinmurali/anaconda3/envs/tensorflows/lib/python3.11/site-packages/tf_keras/src/engine/training.py", line 1381, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/Users/sachinmurali/anaconda3/envs/tensorflows/lib/python3.11/site-packages/tf_keras/src/engine/training.py", line 1370, in run_step  **
        outputs = model.train_step(data)
    File "/Users/sachinmurali/anaconda3/envs/tensorflows/lib/python3.11/site-packages/tf_keras/src/engine/training.py", line 1147, in train_step
        y_pred = self(x, training=True)
    File "/Users/sachinmurali/anaconda3/envs/tensorflows/lib/python3.11/site-packages/tf_keras/src/utils/traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/var/folders/c7/z9xcy1l1481bm3hgrydzvlxm0000gn/T/__autograph_generated_filesfd_5c7n.py", line 74, in tf__call
        ag__.if_stmt(ag__.not_(ag__.ld(self)._has_training_argument), if_body_3, else_body_3, get_state_3, set_state_3, ('result', 'training'), 1)
    File "/var/folders/c7/z9xcy1l1481bm3hgrydzvlxm0000gn/T/__autograph_generated_filesfd_5c7n.py", line 37, in if_body_3
        result = ag__.converted_call(ag__.ld(f), (), None, fscope)

    TypeError: Exception encountered when calling layer 'keras_layer_1' (type KerasLayer).
    
    in user code:
    
        File "/Users/sachinmurali/anaconda3/envs/tensorflows/lib/python3.11/site-packages/tensorflow_hub/keras_layer.py", line 242, in call  *
            result = f()
    
        TypeError: Binding inputs to tf.function failed due to `Can not cast TensorSpec(shape=(None, None), dtype=tf.string, name=None) to TensorSpec(shape=(None,), dtype=tf.string, name=None)`. Received args: (<tf.Tensor 'IteratorGetNext:0' shape=(None, None) dtype=string>,) and kwargs: {} for signature: (sentences: TensorSpec(shape=(None,), dtype=tf.string, name=None)).
    
    
    Call arguments received by layer 'keras_layer_1' (type KerasLayer):
      • inputs=tf.Tensor(shape=(None, None), dtype=string)
      • training=True
