In [1]:
import tensorflow as tf

tf.__version__

'2.19.0'

In [2]:
# random tensor

In [4]:
random_1 = tf.random.Generator.from_seed(42)

random_1.normal(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

In [11]:
tf.random.Generator.from_seed(43)
tf.random.normal(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-2.6461542 , -0.968011  ,  0.1788227 ],
       [-0.68169993, -0.01959211,  0.6233301 ]], dtype=float32)>

In [19]:
# shuffle a tensor
a = tf.constant([[1,2,3],
                 [4,5,6],
                 [8,9,0]])

a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 0]], dtype=int32)>

In [57]:
tf.random.set_seed(42)
tf.random.shuffle(a, seed=42)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 0]], dtype=int32)>