In [1]:
import tensorflow as tf

In [3]:
tf.ones(shape=(3,2), dtype=tf.int16)

<tf.Tensor: shape=(3, 2), dtype=int16, numpy=
array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int16)>

In [5]:
tf.zeros(shape=(2,2), dtype=tf.float64)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0., 0.],
       [0., 0.]])>

In [13]:
# Turn numpy array into tensors
import numpy as np

a = np.arange(1,9, dtype=np.int16)
a

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int16)

In [20]:
tf.constant(a, shape=(1,2,4))

<tf.Tensor: shape=(1, 2, 4), dtype=int16, numpy=
array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]], dtype=int16)>

In [24]:
# create an rank 4 tensor( 4 dim tensor)

rank_4_tensor = tf.zeros(shape=(1,2,3,4))

rank_4_tensor

<tf.Tensor: shape=(1, 2, 3, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [31]:
rank_4_tensor[0]

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [37]:
rank_4_tensor.shape,  rank_4_tensor.ndim

(TensorShape([1, 2, 3, 4]), 4)

In [38]:
tf.size(rank_4_tensor) # number of items

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [46]:
print(f"Data type of the tensor : {rank_4_tensor.dtype}")
print(f"Shape of the tensor: {rank_4_tensor.shape}")
print(f"Rank of the tensor :  {rank_4_tensor.ndim}")
print(f"Total num of elements : {tf.size(rank_4_tensor)}")

print(f"elements in 0th dim : {rank_4_tensor.shape[0]}")


Data type of the tensor : <dtype: 'float32'>
Shape of the tensor: (1, 2, 3, 4)
Rank of the tensor :  4
Total num of elements : 24
elements in 0th dim : 1


In [51]:
c = tf.constant(10)
c.numpy()

np.int32(10)