In [4]:
import tensorflow as tf

tf.__version__


'2.19.0'

In [10]:
rank_4_tensor = tf.ones(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [21]:
rank_4_tensor[:2, :2, :2, :0]

<tf.Tensor: shape=(2, 2, 2, 0), dtype=float32, numpy=array([], shape=(2, 2, 2, 0), dtype=float32)>

In [20]:
my_list = [1,2,3,4,5]

my_list[:0]

[]

In [24]:
rank_2_tensor = tf.ones(shape=(1,2))
rank_2_tensor.ndim

2

In [27]:
rank_2_tensor[:, -1]

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [34]:
rank_2_tensor = tf.constant([[[1,2,4],
                             [4,5,6],
                             [7,8,9]]])

rank_2_tensor

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[1, 2, 4],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int32)>

In [36]:
rank_2_tensor[:, :, 0]

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 4, 7]], dtype=int32)>

In [49]:
rank_2_tensor

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[1, 2, 4],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int32)>

In [43]:
# add a new dim
rank_3_tensor = rank_2_tensor[tf.newaxis] 

rank_3_tensor

<tf.Tensor: shape=(1, 1, 3, 3), dtype=int32, numpy=
array([[[[1, 2, 4],
         [4, 5, 6],
         [7, 8, 9]]]], dtype=int32)>

In [52]:
# another way to add new dim

tf.expand_dims(rank_2_tensor, axis=2)

<tf.Tensor: shape=(1, 3, 1, 3), dtype=int32, numpy=
array([[[[1, 2, 4]],

        [[4, 5, 6]],

        [[7, 8, 9]]]], dtype=int32)>

In [53]:
rank_2_tensor

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[1, 2, 4],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int32)>