In [1]:
import tensorflow as tf

tf.__version__

'2.19.0'

In [3]:
a = tf.constant([[1,2,3],
             [5,6,7]])

a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [5, 6, 7]], dtype=int32)>

In [4]:
a + 10

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [15, 16, 17]], dtype=int32)>

In [5]:
a -10

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[-9, -8, -7],
       [-5, -4, -3]], dtype=int32)>

In [7]:
tf.add(a , 100)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[101, 102, 103],
       [105, 106, 107]], dtype=int32)>

In [9]:
tf.multiply(a  , 100)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[100, 200, 300],
       [500, 600, 700]], dtype=int32)>