In [1]:
import tensorflow as tf

In [4]:
a = tf.constant([[1,2,3],
                 [4,5,6]])


tf.matmul(a,tf.transpose(a))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

In [33]:
a = tf.ones(shape=(2,3))
b = tf.ones(shape=(2,3))


a.shape, b.shape


(TensorShape([2, 3]), TensorShape([2, 3]))

In [24]:
tf.matmul(a,tf.transpose(b))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 3.],
       [3., 3.]], dtype=float32)>

In [27]:
a.shape

TensorShape([2, 3, 4])

In [29]:
a.shape

TensorShape([2, 3, 4])

In [30]:
tf.reshape(a, (3,4,2))

<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]], dtype=float32)>

In [31]:
a.shape

TensorShape([2, 3, 4])

In [34]:
a.shape, b.shape

(TensorShape([2, 3]), TensorShape([2, 3]))

In [38]:
tf.matmul(a,tf.reshape(b,(3,2)))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 3.],
       [3., 3.]], dtype=float32)>