In [2]:
import tensorflow as tf


one = tf.constant([-8.0, 100])

one

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ -8., 100.], dtype=float32)>

In [3]:
tf.abs(one)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([  8., 100.], dtype=float32)>

In [16]:
import numpy as np

b = tf.constant(np.random.randint(4,10, size=5))
b

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([5, 8, 4, 4, 5])>

In [17]:
tf.size(b),  b.shape, b.dtype

(<tf.Tensor: shape=(), dtype=int32, numpy=5>, TensorShape([5]), tf.int64)

In [18]:
tf.reduce_min(b)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [20]:
tf.reduce_max(b)

<tf.Tensor: shape=(), dtype=int64, numpy=8>

In [21]:
tf.reduce_mean(b)

<tf.Tensor: shape=(), dtype=int64, numpy=5>

In [22]:
tf.reduce_sum(b)

<tf.Tensor: shape=(), dtype=int64, numpy=26>

In [29]:
c = tf.random.uniform(shape=[10])
c

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.8593806 , 0.22241247, 0.883477  , 0.72283876, 0.10507083,
       0.7896459 , 0.98112726, 0.28661394, 0.11530709, 0.24053359],
      dtype=float32)>

In [31]:
tf.argmin(c)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [32]:
tf.reduce_max(c)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9811272621154785>