In [1]:
import tensorflow as tf


tf.__version__

'2.19.0'

In [22]:
tf.random.set_seed(42)
a = tf.random.uniform(shape=(2,10))
a

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686],
       [0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ]],
      dtype=float32)>

In [23]:
a.shape

TensorShape([2, 10])

In [28]:
g_sq  =tf.squeeze(a).shape
g_sq

TensorShape([2, 10])

In [36]:
some_list = [0,1,1,2,3,1]

tf.one_hot(some_list, depth=10, on_value="sam", off_value="ray") 

<tf.Tensor: shape=(6, 10), dtype=string, numpy=
array([[b'sam', b'ray', b'ray', b'ray', b'ray', b'ray', b'ray', b'ray',
        b'ray', b'ray'],
       [b'ray', b'sam', b'ray', b'ray', b'ray', b'ray', b'ray', b'ray',
        b'ray', b'ray'],
       [b'ray', b'sam', b'ray', b'ray', b'ray', b'ray', b'ray', b'ray',
        b'ray', b'ray'],
       [b'ray', b'ray', b'sam', b'ray', b'ray', b'ray', b'ray', b'ray',
        b'ray', b'ray'],
       [b'ray', b'ray', b'ray', b'sam', b'ray', b'ray', b'ray', b'ray',
        b'ray', b'ray'],
       [b'ray', b'sam', b'ray', b'ray', b'ray', b'ray', b'ray', b'ray',
        b'ray', b'ray']], dtype=object)>

In [37]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]