In [3]:
# import tensorflow
import tensorflow as tf

tf.__version__


'2.19.0'

In [4]:
# create a scalar tensor

scalar = tf.constant(10)

scalar

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [7]:
# check the dimension

scalar.ndim , scalar.shape, scalar.dtype

(0, TensorShape([]), tf.int32)

np.int32(10)

In [10]:
# create  a vector

vector = tf.constant([1,2,3,4,5])

vector

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [13]:
vector.shape,  vector.dtype, vector.ndim

(TensorShape([5]), tf.int32, 1)

In [14]:
# create a matrix

matrix = tf.constant([[1,2,3],
                      [4,5,6]])

matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [17]:
matrix.shape, matrix.ndim ,matrix.dtype

(TensorShape([2, 3]), 2, tf.int32)

In [22]:
# create anothet matrix

another_matric = tf.constant([[1,2,3,4],
                              [5.0, 6.0,7.0, 8.0]], dtype=tf.float16)

In [23]:
another_matric

<tf.Tensor: shape=(2, 4), dtype=float16, numpy=
array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float16)>

In [24]:
another_matric.ndim

2

In [35]:
# chnagable vs unchangable tensor

changable_tensor = tf.Variable([10,10])
un_chnagable_tensor = tf.constant([10,10])

In [36]:
un_changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>

In [39]:
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>

In [40]:
changable_tensor[0].assign(29)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([29, 10], dtype=int32)>

In [42]:
changable_tensor.assign([100,200])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([100, 200], dtype=int32)>