In [9]:
import tensorflow as tf

tf.__version__

'2.19.0'

In [10]:
scalar = tf.constant([[1,2,3],
                      [4,5,6]])

scalar

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [11]:
scalar.ndim

2

In [12]:
scalar.dtype

tf.int32

In [13]:
scalar.shape

TensorShape([2, 3])

In [14]:
tf.size(scalar).numpy().item()


6

In [15]:
# varibale vs constant
variable = tf.Variable([100])
variable


<tf.Variable 'Variable:0' shape=(1,) dtype=int32, numpy=array([100], dtype=int32)>

In [16]:
variable[0].assign(200)

<tf.Variable 'UnreadVariable' shape=(1,) dtype=int32, numpy=array([200], dtype=int32)>

In [17]:
variable.dtype

tf.int32

In [18]:
# create ra ndoim ten sor
tf.random.set_seed(42)
tf.random.Generator.from_seed(42)

tf.random.normal(shape=(10,))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([ 0.3274685 , -0.8426258 ,  0.3194337 , -1.4075519 , -2.3880599 ,
       -1.0392479 , -0.5573232 ,  0.539707  ,  1.6994323 ,  0.28893656],
      dtype=float32)>

In [64]:
import torch
torch.manual_seed(42)
torch.rand(size=(2,5))

tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
        [0.6009, 0.2566, 0.7936, 0.9408, 0.1332]])

In [37]:
# tf.random.set_seed(42)
seeds = tf.random.Generator.from_seed(42)
seeds.normal(shape=(1,3))

tf.random.normal((1,3))

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-1.588346  ,  0.80656034, -0.2999747 ]], dtype=float32)>

In [81]:
tf.random.set_seed(42)
c = tf.random.uniform(shape=(2,5))
c

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041],
       [0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686]],
      dtype=float32)>

In [88]:
tf.random.shuffle(c)

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686],
       [0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041]],
      dtype=float32)>

In [92]:
one = tf.ones(shape=(2,3))
one

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [97]:
zero = tf.zeros(shape=(3,4))
zero

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [101]:
# maniupulating tensors
zero + 100

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]], dtype=float32)>

In [144]:
tf.random.set_seed(42)
a = tf.random.normal(shape=(2,3))
tf.random.set_seed(42)
b = tf.random.normal(shape=(2,2))

a, b

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[ 0.3274685, -0.8426258,  0.3194337],
        [-1.4075519, -2.3880599, -1.0392479]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 0.3274685, -0.8426258],
        [ 0.3194337, -1.4075519]], dtype=float32)>)

In [148]:
tf.matmul(tf.reshape(a, (1,3,2)),b)

<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[-0.16192745,  0.9101061 ],
        [-0.34501502,  1.7120392 ],
        [-1.1139852 ,  3.4750361 ]]], dtype=float32)>

In [150]:
tf.reshape(a, (3,1,2)).shape

TensorShape([3, 1, 2])

In [153]:
a = tf.random.uniform((1,2,3))
a


<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[0.7402308 , 0.33938193, 0.5692506 ],
        [0.44811392, 0.29285502, 0.4260056 ]]], dtype=float32)>

In [157]:
a.shape , a.ndim , tf.size(a),  a.dtype

(TensorShape([1, 2, 3]),
 3,
 <tf.Tensor: shape=(), dtype=int32, numpy=6>,
 tf.float32)

In [168]:
c = tf.reshape(a, (3,2,1))

c

<tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
array([[[0.7402308 ],
        [0.33938193]],

       [[0.5692506 ],
        [0.44811392]],

       [[0.29285502],
        [0.4260056 ]]], dtype=float32)>

In [173]:
tf.cast(c, dtype=tf.float16)

<tf.Tensor: shape=(3, 2, 1), dtype=float16, numpy=
array([[[0.74  ],
        [0.3394]],

       [[0.5693],
        [0.448 ]],

       [[0.293 ],
        [0.426 ]]], dtype=float16)>

In [190]:
a = tf.random.normal((1,2,3))
a

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[-0.4588769 , -1.5503484 ,  1.2272254 ],
        [-0.02246891, -0.36805412,  0.06950591]]], dtype=float32)>

In [191]:
tf.abs(a)

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[0.4588769 , 1.5503484 , 1.2272254 ],
        [0.02246891, 0.36805412, 0.06950591]]], dtype=float32)>

In [207]:
tf.reduce_min(a), tf.reduce_max(a), tf.reduce_mean(a), tf.reduce_sum(a)

a

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[-0.4588769 , -1.5503484 ,  1.2272254 ],
        [-0.02246891, -0.36805412,  0.06950591]]], dtype=float32)>

In [214]:
tf.argmin(a, axis=2)

<tf.Tensor: shape=(1, 2), dtype=int64, numpy=array([[1, 1]])>

In [199]:
a.shape

TensorShape([1, 2, 3])